### ISSUE TITLE
predict by day

### ISSUE THREAD

**Issue by panda403** [signaflo/java-timeseries#28]
Hello,after i read the API documentation(https://javadoc.io/doc/com.github.signaflo/timeseries/0.4),I found that the new TimeSeries only have weekly、monthly or quarterly predict,but I want to do the model predicted by the day,my data changes over the weekend(it low in weekend,high in workday),is there has any other way to predict my data using ARIMA?Did i use TimeSeries.from(double[] d) works out best predict?waiting for your replay,@signaflo

**Comment by signaflo** [comment]
@panda403 , I know there's currently a lack of good documentation on how to use this library. 

I'll create a new wiki page based on what we discuss here.

You have daily data and you want to make the predictions in a seasonal manner?

**Comment by signaflo** [comment]
@panda403 ,

Please take a look at this wiki page and let me know if it helps with your issue.

https://github.com/signaflo/java-timeseries/wiki/Example%20of%20daily%20predictions%20with%20weekly%20seasonality

**Comment by panda403** [comment]
Thank you for your reply! I test the code in your wiki,it seems exactly what i need,Thks！
